spring.application.name=CourseManagementApplication

spring.datasource.url=jdbc:postgresql://aws-1-ca-central-1.pooler.supabase.com:5432/postgres?user=postgres.cmidlbqkcqsxnbvlbiaq&password=Yogeshwari@24
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081